docs:
  - changed-files:
    - any-glob-to-any-file:
      - README.md
      - RELEASE_NOTES.md

internal:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**
      - scripts/**
      - .gitignore
      - .pre-commit-config.yaml
      - uv.lock
