import json

from typing import Any

from fastapi.encoders import jsonable_encoder
from fastapi.openapi.docs import swagger_ui_default_parameters
from starlette.responses import HTMLResponse, Response


def _html_safe_json(value: Any) -> str:
    """Serialize a value to JSON with HTML special characters escaped.

    This prevents injection when the JSON is embedded inside a <script> tag.
    """
    return json.dumps(value).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")


def get_swagger_ui_init_js(
    *,
    openapi_url: str,
    oauth2_redirect_url: str | None = None,
    init_oauth: dict[str, Any] | None = None,
    swagger_ui_parameters: dict[str, Any] | None = None,
) -> Response:
    """
    Generate and return the response that initializes Swagger UI.

    This is normally served as `swagger-initializer.js`, referenced from the
    HTML generated by [get_swagger_ui_html][fastapi_csp_docs.docs.get_swagger_ui_html].

    You would only call this function yourself if you needed to override some parts,
    for example to serve the initializer script from your own endpoint.

    :param openapi_url: URL of the OpenAPI schema for Swagger UI to render.
    :param oauth2_redirect_url: URL of the OAuth2 redirect endpoint, or None to disable
        OAuth2 login in the UI.
    :param init_oauth: OAuth2 configuration passed to `ui.initOAuth()`, or None to skip it.
    :param swagger_ui_parameters: extra Swagger UI parameters merged over FastAPI's defaults.
    """
    current_swagger_ui_parameters = swagger_ui_default_parameters.copy()
    if swagger_ui_parameters:
        current_swagger_ui_parameters.update(swagger_ui_parameters)

    js = f"""
    window.onload = function() {{
    const ui = SwaggerUIBundle({{
        url: '{openapi_url}',
    """

    for key, value in current_swagger_ui_parameters.items():
        js += f"{_html_safe_json(key)}: {_html_safe_json(jsonable_encoder(value))},\n"

    if oauth2_redirect_url:
        js += f"oauth2RedirectUrl: window.location.origin + '{oauth2_redirect_url}',"

    js += """
    presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
    })"""

    if init_oauth:
        js += f"""
        ui.initOAuth({_html_safe_json(jsonable_encoder(init_oauth))})
        """

    js += """
    window.ui = ui;
    };
    """
    return Response(content=js, media_type="text/javascript")


def get_swagger_ui_html(
    *,
    title: str,
    swagger_js_url: str = "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js",
    swagger_css_url: str = "https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css",
    swagger_favicon_url: str = "https://fastapi.tiangolo.com/img/favicon.png",
    swagger_ui_init_script_url: str = "/docs/swagger-initializer.js",
) -> HTMLResponse:
    """
    Generate and return the HTML that loads Swagger UI for the interactive
    API docs (normally served at `/docs`).

    You would only call this function yourself if you needed to override some parts,
    for example the URLs to use to load Swagger UI's JavaScript and CSS.

    Read more about it in the
    [FastAPI docs for Configure Swagger UI](https://fastapi.tiangolo.com/how-to/configure-swagger-ui/).

    :param title: HTML page title.
    :param swagger_js_url: URL of the Swagger UI JavaScript bundle.
    :param swagger_css_url: URL of the Swagger UI CSS.
    :param swagger_favicon_url: URL of the favicon.
    :param swagger_ui_init_script_url: URL of the script that initializes Swagger UI, see
        [get_swagger_ui_init_js][fastapi_csp_docs.docs.get_swagger_ui_init_js].
    """
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" href="{swagger_css_url}">
    <link rel="shortcut icon" href="{swagger_favicon_url}">
    </head>
    <body>
    <div id="swagger-ui"></div>
    <script src="{swagger_js_url}" charset="UTF-8"></script>
    <!-- `SwaggerUIBundle` is now available on the page -->
    <script src="{swagger_ui_init_script_url}" charset="UTF-8"></script>
    </body>
    </html>
    """
    return HTMLResponse(html)


def get_redoc_html(
    *,
    openapi_url: str,
    title: str,
    redoc_js_url: str = "https://cdn.jsdelivr.net/npm/redoc@2/bundles/redoc.standalone.js",
    redoc_favicon_url: str = "https://fastapi.tiangolo.com/img/favicon.png",
    with_google_fonts: bool = True,
    redoc_css_url: str = "/redoc/redoc.css",
    google_fonts_css_url: str = "https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700",
    disable_search: bool = False,
) -> HTMLResponse:
    """
    Generate and return the HTML response that loads ReDoc for the alternative
    API docs (normally served at `/redoc`).

    You would only call this function yourself if you needed to override some parts,
    for example the URLs to use to load ReDoc's JavaScript and CSS.

    :param openapi_url: URL of the OpenAPI schema for ReDoc to render.
    :param title: HTML page title.
    :param redoc_js_url: URL of the ReDoc JavaScript bundle.
    :param redoc_favicon_url: URL of the favicon.
    :param with_google_fonts: whether to load the Montserrat/Roboto fonts from Google Fonts.
    :param redoc_css_url: URL of the CSS reset required by ReDoc, see
        [get_redoc_css][fastapi_csp_docs.docs.get_redoc_css].
    :param google_fonts_css_url: URL of the Google Fonts stylesheet, used only when
        `with_google_fonts` is True.
    :param disable_search: whether to disable ReDoc's client-side search box (and the Web
        Worker it runs in) — see the README section on `worker-src`.
    """
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <title>{title}</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    """
    if with_google_fonts:
        html += f"""
    <link href="{google_fonts_css_url}" rel="stylesheet">
    """
    html += f"""
    <link rel="shortcut icon" href="{redoc_favicon_url}">
    <link rel="stylesheet" type="text/css" href="{redoc_css_url}">
    <!--
    ReDoc doesn't change outer page styles
    -->
    </head>
    <body>
    <noscript>
        ReDoc requires Javascript to function. Please enable it to browse the documentation.
    </noscript>
    <redoc spec-url="{openapi_url}"{' disable-search="true"' if disable_search else ""}></redoc>
    <script src="{redoc_js_url}"> </script>
    </body>
    </html>
    """
    return HTMLResponse(html)


def get_redoc_css() -> Response:
    """
    Generate and return the response with the CSS reset required by ReDoc.

    This is normally served as `redoc.css`, referenced from the HTML
    generated by [get_redoc_html][fastapi_csp_docs.docs.get_redoc_html].

    You normally don't need to use or change this.
    """
    return Response(content="body{margin:0;padding:0;}", media_type="text/css")


def get_swagger_ui_oauth2_redirect_html(
    *,
    oauth2_redirect_script_url: str = "oauth2-redirect.js",
) -> HTMLResponse:
    """
    Generate the HTML response with the OAuth2 redirection for Swagger UI.

    You would only call this function yourself if you needed to override some parts,
    for example the URL of the OAuth2 redirect script.

    :param oauth2_redirect_script_url: URL of the OAuth2 redirect script, see
        [get_swagger_ui_oauth2_redirect_js][fastapi_csp_docs.docs.get_swagger_ui_oauth2_redirect_js].
    """
    html = f"""
    <!doctype html>
    <html lang="en-US">
    <head>
        <title>Swagger UI: OAuth2 Redirect</title>
    </head>
    <body>
    <script src="{oauth2_redirect_script_url}"></script>
    </body>
    </html>
    """
    return HTMLResponse(content=html)


def get_swagger_ui_oauth2_redirect_js() -> Response:
    """
    Generate and return the response with the OAuth2 redirection logic for
    Swagger UI.

    This is normally served as `oauth2-redirect.js`, referenced from the HTML
    generated by
    [get_swagger_ui_oauth2_redirect_html][fastapi_csp_docs.docs.get_swagger_ui_oauth2_redirect_html].

    You normally don't need to use or change this.
    """
    # minified, copied from https://github.com/swagger-api/swagger-ui/blob/v5.32.8/dist/oauth2-redirect.js
    js = (
        '"use strict";function run(){var e,r,t,a=window.opener.swaggerUIRedirectOauth2,'
        "o=a.state,n=a.redirectUrl;if((t=(r=/code|token|error/.test(window.location.hash)?"
        'window.location.hash.substring(1).replace("?","&"):location.search.substring(1))'
        '.split("&")).forEach((function(e,r,t){t[r]=\'"\'+e.replace("=",\'":"\')+\'"\'})),'
        'e=(r=r?JSON.parse("{"+t.join()+"}",(function(e,r){return""===e?r:decodeURIComponent(r)}))'
        ':{}).state===o,"accessCode"!==a.auth.schema.get("flow")&&"authorizationCode"!=='
        'a.auth.schema.get("flow")&&"authorization_code"!==a.auth.schema.get("flow")||a.auth.code)'
        "a.callback({auth:a.auth,token:r,isValid:e,redirectUrl:n});else if(e||a.errCb({authId:"
        'a.auth.name,source:"auth",level:"warning",message:"Authorization may be unsafe, passed '
        "state was changed in server Passed state wasn't returned from auth server\"}),r.code)"
        "delete a.state,a.auth.code=r.code,a.callback({auth:a.auth,redirectUrl:n});else{let e;"
        'r.error&&(e="["+r.error+"]: "+(r.error_description?r.error_description+". ":"no accessCode '
        'received from the server. ")+(r.error_uri?"More info: "+r.error_uri:"")),a.errCb({authId:'
        'a.auth.name,source:"auth",level:"error",message:e||"[Authorization failed]: no accessCode '
        'received from the server"})}window.close()}"loading"!==document.readyState?run():'
        'document.addEventListener("DOMContentLoaded",(function(){run()}));'
    )
    return Response(content=js, media_type="text/javascript")
